name: Telegram Bot Server

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  bot:
    runs-on: ubuntu-latest
    timeout-minutes: 350

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Telegram Bot
        env:
          FIREBASE_DB_URL: ${{ secrets.FIREBASE_DB_URL }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          BOT_PASSWORD: ${{ secrets.BOT_PASSWORD }}
        run: node .github/scripts/bot.js
